<?xml version="1.0" encoding="UTF-8"?>
<testsuite failures="5" tests="8" errors="0" name="Tests" skip="0">
<testcase classname="Tests.Test.HelloWorld" name="HelloWorld" time="0">
</testcase>
<testcase classname="Tests.Test.TestDebugSetup" name="Test Debug Setup Index" time="7">
</testcase>
<testcase classname="Tests.Test.TestDebugSetup" name="Test Debug Setup Swagger" time="7">
<failure message="Text '/todos' did not appear in 5 seconds." type="AssertionError"></failure>
</testcase>
<testcase classname="Tests.Test.TestDebugSetup" name="Test Debug Setup PhpMyAdmin" time="2">
</testcase>
<testcase classname="Tests.Test.TestServiceBackend" name="Test Service Index Todos Unhappy1" time="1">
<failure message="ConnectionError: HTTPConnectionPool(host='ufp-sidt-example-app', port=3000): Max retries exceeded with url: /todos (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f978672aa90&gt;: Failed to establish a new connection: [Errno -2] Name does not resolve',))" type="AssertionError"></failure>
</testcase>
<testcase classname="Tests.Test.TestServiceBackend" name="Test Service Index Todos Unhappy2" time="1">
<failure message="ConnectionError: HTTPConnectionPool(host='ufp-sidt-example-app', port=3000): Max retries exceeded with url: /todos (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f97866ef7d0&gt;: Failed to establish a new connection: [Errno -2] Name does not resolve',))" type="AssertionError"></failure>
</testcase>
<testcase classname="Tests.Test.TestServiceBackend" name="Test Service Index Todos Happy" time="1">
<failure message="ConnectionError: HTTPConnectionPool(host='ufp-sidt-example-app', port=3000): Max retries exceeded with url: /todos (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f978673b350&gt;: Failed to establish a new connection: [Errno -2] Name does not resolve',))" type="AssertionError"></failure>
</testcase>
<testcase classname="Tests.Test.TestServiceFrontend" name="Test Service Index Todos" time="7">
<failure message="Text 'UfpCore' did not appear in 5 seconds." type="AssertionError"></failure>
</testcase>
</testsuite>
